Backup: Add containers dump to backup-server minor changes to other backup correct source GLOBAL_FUNCTIONS & S_GLOBAL_CONF correct _get_ip & _get_ipv6 for /usr/local/bs

diff --git a/backup-vz b/backup-vz
--- a/backup-vz
+++ b/backup-vz
@@ -7,12 +7,14 @@
 ################################ GLOBAL FUNCTIONS
 #S_TRACE=debug
 
-! [[ "$S_GLOBAL_FUNCTIONS" && -f $S_GLOBAL_FUNCTIONS ]] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
-. $S_GLOBAL_FUNCTIONS
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
+
+! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
+. "$S_GLOBAL_FUNCTIONS"
 
 ################################  VARIABLES
 
-USAGE="backup-vz : backup vz configuration, dump & templates.
+usage="backup-vz : backup vz configuration, dump & templates.
 Default backup all, equivalent to -ctduosl
 Use other options for a selected save
 backup-vz --help
@@ -36,34 +38,36 @@ options:
 # $1 path base
 # $2 sub path
 __compress() {
-	PATHFROM="$1"
-	PATHSUBS="$2"
-	PATH2="${PATHFROM#/}"; PATH2="$PATHSAVE/${PATH2//\//.}"; PATH2="${PATH2%/}"
-	_echoD "$FUNCNAME:$LINENO PATHFROM='$PATHFROM' PATHSUBS='$PATHSUBS' PATH2='$PATH2'"
+	local path_from="$1"
+	local path_subs="$2"
+	local path_to
+
+	path_to="${path_from#/}"; path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
+	_echoD "$FUNCNAME:$LINENO path_from='$path_from' path_subs='$path_subs' path_to='$path_to'"
 
 	# wrong path
-	! [ -d "$PATHFROM" ] && _exite "Wrong path '$PATHFROM' for calling '$*'"
+	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
 
 	# create path
-	! [ -d "$PATH2" ] && mkdir -p "$PATH2"
+	! [ -d "$path_to" ] && mkdir -p "$path_to"
 
-	cd "$PATHFROM"
+	cd "$path_from"
 	_echoT "$PWD"
 
-	PATHSUBS=$(echo "$PATHSUBS")
+	path_subs=$(echo "$path_subs")
 
-	for PATHSUB in $PATHSUBS
+	for path_sub in $path_subs
 	do
-		if [ -d "$PATHSUB" ]; then
-			FILE2="${PATHSUB#/}"
-			FILE2="${FILE2//\//.}"
-			FILE2="$PATH2/${FILE2%/}.$CMPEXT"
+		if [ -d "$path_sub" ]; then
+			file2="${path_sub#/}"
+			file2="${file2//\//.}"
+			file2="$path_to/${file2%/}.$comp_ext"
 
-			_echo "compress $PATHSUB"
-			_evalq "tar $CMPOPT $FILE2 $PATHSUB"
+			_echo "compress $path_sub"
+			_evalq "tar $comp_opt $file2 $path_sub"
 		else
-			_echoE "wrong path '$PATHSUB'"
-			_echoD "$FUNCNAME:$LINENO ERROR| Wrong path '$PATHSUB'"
+			_echoE "wrong path '$path_sub'"
+			_echoD "$FUNCNAME:$LINENO ERROR| Wrong path '$path_sub'"
 		fi
 	done
 }
@@ -73,35 +77,58 @@ __compress() {
 # $2 sub path
 # $3 exclude path
 __sync() {
-	PATHFROM="$1"
-	PATHSUBS="$2"
-	EXCLUDES="lost+found $3"
-	PATH2="${PATHFROM#/}"; PATH2="$PATHSAVE/${PATH2//\//.}"; PATH2="${PATH2%/}"
-	_echoD "$FUNCNAME:$LINENO PATHFROM='$PATHFROM' PATHSUBS='$PATHSUBS' PATH2='$PATH2'"
+	local path_from="$1"
+	local path_subs="$2"
+	local excludes="lost+found $3"
+	local path_to="${path_from#/}"
+
+	path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
+	_echoD "$FUNCNAME:$LINENO path_from='$path_from' path_subs='$path_subs' path_to='$path_to'"
 
 	# wrong path
-	! [ -d "$PATHFROM" ] && _exite "Wrong path '$PATHFROM' for calling '$*'"
+	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
 
 	# create path
-	! [ -d "$PATH2" ] && mkdir -p "$PATH2"
+	! [ -d "$path_to" ] && mkdir -p "$path_to"
 
-	cd "$PATH2"
+	cd "$path_to"
 	_echoT "$PWD"
 
-	for PATHSUB in $PATHSUBS
+	for path_sub in $path_subs
 	do
-		if [ -d "$PATHFROM/$PATHSUB" ]; then
-			PATHSUB2="${PATH2}/${PATHSUB#/}"
-			! [ -d "$PATHSUB2" ] && mkdir -p "$PATHSUB2"
+		if [ -d "$path_from/$path_sub" ]; then
+			path_sub_to="${path_to}/${path_sub#/}"
+			! [ -d "$path_sub_to" ] && mkdir -p "$path_sub_to"
 
-			STR=; for exclude in $EXCLUDES; do STR+=" --exclude='$exclude'"; done
-			_echo "sync $PATHSUB"
-			_evalq "rsync -a $STR $PATHFROM/$PATHSUB/ $PATHSUB2/"
+			str=; for exclude in $excludes; do str+=" --exclude='$exclude'"; done
+			_echo "sync $path_sub"
+			_evalq "rsync -a $str $path_from/$path_sub/ $path_sub_to/"
 		else
-			_echoE "wrong path '$PATHFROM/$PATHSUB'"
-			_echoD "$FUNCNAME:$LINENO ERROR| Wrong path '$PATHFROM/$PATHSUB'"
+			_echoE "wrong path '$path_from/$path_sub'"
+			_echoD "$FUNCNAME:$LINENO ERROR| Wrong path '$path_from/$path_sub'"
 		fi
 	done
+}
+
+
+__comp_share() {
+	local paths path
+
+	# all paths except mariadb & www
+	paths=`ls "${S_HOSTING_PATH_SHARE}"|grep -v mariadb|grep -v www`
+	for path in ${paths}; do
+		__compress "${S_HOSTING_PATH_SHARE}" "${path}"
+	done
+	# for mariadb & www
+	#_echoT "STOP CONTAINER FROM 101 to 199"
+	#vz-ctl stop 101-199
+	#_echoT "Container stopped"
+	for path in www; do
+		[ -d "${S_HOSTING_PATH_SHARE}/${path}" ] && __compress "${S_HOSTING_PATH_SHARE}/${path}" "*"
+	done
+	#_echoT "START CONTAINER FROM 101 to 199"
+	#vz-ctl start 101-199
+	#_echoT "Container started"
 }
 
 
@@ -109,88 +136,87 @@ __sync() {
 
 _echoD "$FUNCNAME:$LINENO $_SCRIPT / $(date +"%d-%m-%Y %T : %N") ---- start"
 
-DATE="$(date "+%Y%m%d")"
-PATHSAVE="$S_PATH_SAVE/$HOSTNAME/backup/$DATE/vz"
-CMPOPT=czf
-CMPEXT=tgz
+path_save="$S_PATH_SAVE_BACKUP/$DDATE/vz"
+comp_opt=czf
+comp_ext=tgz
 
-OPTSGIVEN="$@"
-OPTSSHORT="cdloqstu"
-OPTSLONG="help,debug,conf,dump,log,snapshot,quiet,share,template,suspend"
-OPTS=$(getopt -o $OPTSSHORT -l $OPTSLONG -n "${0##*/}" -- "$@" 2>/tmp/${0##*/}) || _exite "wrong options '$(</tmp/${0##*/})'"
+opts_given="$@"
+opts_short="cdloqstu"
+opts_long="help,debug,conf,dump,log,snapshot,quiet,share,template,suspend"
+OPTS=$(getopt -o $opts_short -l $opts_long -n "${0##*/}" -- "$@" 2>/tmp/${0##*/}) || _exite "wrong options '$(</tmp/${0##*/})'"
 eval set -- "$OPTS"
 
-_echoD "$FUNCNAME:$LINENO OPTSGIVEN='$OPTSGIVEN' OPTS='$OPTS'"
+_echoD "$FUNCNAME:$LINENO opts_given='$opts_given' OPTS='$OPTS'"
 while true; do
 	case "$1" in
 		--help)
-			_echo "$USAGE"; _exit
+			_echo "$usage"; _exit
 			;;
 		--debug)
 			_redirect debug
 			;;
 		-c|--conf)
-			CONF=c
+			conf=c
 			;;
 		-d|--dump)
-			DUMP=d
+			dump=d
 			;;
 		-l|--log)
-			LOG=l
+			log=l
 			;;
 		-o|--snapshot)
-			SNAPSHOT=o
+			snapshot=o
 			;;
 		-q|--quiet)
 			_redirect quiet
 			;;
 		-s|--share)
-			SHARE=s
+			share=s
 			;;
 		-t|--template)
-			TEMPLATE=t
+			template=t
 			;;
 		-u|--suspend)
-			SUSPEND=u
+			suspend=u
 			;;
 		--)
 			shift
 			break
 			;;
 		*)
-			_exite "Bad options: '$1' in '$OPTSGIVEN'"
+			_exite "Bad options: '$1' in '$opts_given'"
 			;;
 	esac
 	shift
 done
 
 # all options
-# ; LOG=l
-if ! [ "$OPTSGIVEN" ]; then CONF=c; TEMPLATE=t; DUMP=d; SUSPEND=u; SNAPSHOT=o; SHARE=s; fi
-_echoD "$FUNCNAME:$LINENO CONF='$CONF' TEMPLATE='$TEMPLATE' DUMP='$DUMP' SUSPEND='$SUSPEND' SNAPSHOT='$SNAPSHOT' SHARE='$SHARE' LOG='$LOG'"
+# ; log=l
+if ! [ "$opts_given" ]; then conf=c; template=t; dump=d; suspend=u; snapshot=o; share=s; fi
+_echoD "$FUNCNAME:$LINENO conf='$conf' template='$template' dump='$dump' suspend='$suspend' snapshot='$snapshot' share='$share' log='$log'"
+
+# dump all containers, force to stop if not
+vz-dump -cyf all
 
 # conf
-[ "$CONF" ] && __compress "/" "etc/vz etc root/.ssh root"
-
-# dump
-[ "$DUMP" ] && __sync "$S_HOSTING_PATH" "dump" "/suspend /snapshot /template"
-
-# template
-[ "$TEMPLATE" ] && __sync "$S_VZ_PATH_DUMP" "template"
-
-# suspend
-[ "$SUSPEND" ] && __sync "$S_VZ_PATH_DUMP" "suspend"
-
-# snapshot
-[ "$SNAPSHOT" ] && __sync "$S_VZ_PATH_DUMP" "snapshot"
-
-# share
-#[ "$SHARE" ] && __sync "$S_HOSTING_PATH" "share"
-_askno "Please shutdown server with SGBD to compress shared data"
-[ "$SHARE" ] && __compress "$S_HOSTING_PATH_SHARE" "*"
-_askno "Now you can restart server with SGBD"
+[ "$conf" ] && __compress "/" "etc/vz etc root/.ssh root"
 
 # log
-[ "$LOG" ] && __compress "$S_VZ_PATH_NODE" "*/log"
+[ "$log" ] && __compress "$S_VZ_PATH_NODE" "*/log"
+
+# dump
+[ "$dump" ] && __sync "$S_HOSTING_PATH" "dump" "/suspend /snapshot /template"
+
+# template
+[ "$template" ] && __sync "$S_VZ_PATH_DUMP" "template"
+
+# suspend
+[ "$suspend" ] && __sync "$S_VZ_PATH_DUMP" "suspend"
+
+# snapshot
+[ "$snapshot" ] && __sync "$S_VZ_PATH_DUMP" "snapshot"
+
+# share
+[ "$share" ] && __comp_share
 
 _exit 0
diff --git a/inc-functions b/inc-functions
--- a/inc-functions
+++ b/inc-functions
@@ -318,9 +318,10 @@ _pwd32() { < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32; }
 
 _get_ip() {
 	local interface
-	interface="${1:-$(ip -4 -o route show to default|cut -d' ' -f5)}"
+	interface="${1:-$(ip -4 -o route show to default|cut -d' ' -f5|head -n1)}"
 	#ifconfig $inter | sed -n 's|^\s\+inet \(addr:\)\?\([0-9\.]\+\) .*|\2|p'
-	[ "${interface}" ] && ip -br -4 -o address show dev ${interface}|sed 's|.*\s\+\([0-9\.]\+\)/.*|\1|'
+	[ "${interface}" ] && ip -4 -o address show dev ${interface}|sed 's|.*inet\s\([0-9\.]\+\)/.*|\1|'
+	#[ "${interface}" ] && ip -br -4 -o address show dev ${interface}|sed 's|.*\s\+\([0-9\.]\+\)/.*|\1|'
 	# for ip version >= ss190107, with -j option
 	#interface=`ip -4 -j route show to default|jq -r '.[0].dev'`
 	#ip -4 -j address show dev ${interface}|jq -r '.[].addr_info[0].local|select(.!=null)'
@@ -328,9 +329,10 @@ _get_ip() {
 
 _get_ipv6() {
 	local interface
-	interface="${1:-$(ip -6 -o route show to default|cut -d' ' -f5)}"
+	interface="${1:-$(ip -6 -o route show to default|cut -d' ' -f5|head -n1)}"
 	#ifconfig ${interface} | sed -n 's|^\s\+inet6 \(addr:\)\?\([0-9a-z\:]\+\) .*128.*|\2|p'
-	[ "${interface}" ] && ip -br -6 -o address show dev ${interface}|sed 's|.*\s\+\([0-9a-z:]\+\)/128.*|\1|'
+	[ "${interface}" ] && ip -6 -o address show dev ${interface}|sed -n 's|.*inet6\s\([0-9a-z:.]\+\)/128.*|\1|p'
+	#[ "${interface}" ] && ip -br -6 -o address show dev ${interface}|sed 's|.*\s\+\([0-9a-z:]\+\)/128.*|\1|'
 	# for ip version >= ss190107, with -j option
 	#ip -6 -j address show dev ${interface}|jq -r '.[].addr_info[0].local|select(.!=null)'
 }
@@ -543,12 +545,10 @@ DDATE=`date "+%Y%m%d"` # date for log...
 SDATE=`date +%s` # date for keeping file
 
 # global configuration
-if [[ -z "$S_GLOBAL_CONF" || ! -f "$S_GLOBAL_CONF" ]]; then
-	echo -e "${red}alert - value of \$S_GLOBAL_CONF are empty from ${BASH_SOURCE[0]}${cclear}"
-	file="${_PATH_BASE}/conf-init.install"
-	if ! . "$file"; then
-		if ! . /etc/server/server.conf; then echo -e "${redb}error - unable to find file '$file' from ${BASH_SOURCE[0]}${cclear}" && exit 1; fi
-	fi
+S_GLOBAL_CONF="${S_GLOBAL_CONF:-/etc/server/server.conf}"
+if [ ! -f "$S_GLOBAL_CONF" ]; then
+	echo -e "${redb}error - unable to find file '$file' from ${BASH_SOURCE[0]}${cclear}"
+	exit 1
 fi
 . "$S_GLOBAL_CONF"
 
