inc-funtions: big modifications on structure file server.conf: idem others: adaptation of modifications

diff --git a/backup-server b/backup-server
--- a/backup-server
+++ b/backup-server
@@ -5,12 +5,10 @@
 # Description:          backup server, vz & kvm files & configuration
 
 ################################ GLOBAL FUNCTIONS
-#S_TRACE=debug
+S_TRACE=debug
 
 S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
-
-! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
-. "$S_GLOBAL_FUNCTIONS"
+! . "$S_GLOBAL_FUNCTIONS" && echo -e "[error] - Unable to source file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
 
 ################################  VARIABLES
 
@@ -34,10 +32,10 @@ arguments:
 # $1 path base
 # $2 sub path
 __compress() {
-	path_from="$1"
-	paths_sub="$2"
-	path_to="${path_from#/}"; path_to="$path_save/${path_to//\//.}"; path_to="${path_to%/}"
-	_echoD "$FUNCNAME:$LINENO path_from='$path_from' paths_sub='$paths_sub' path_to='$path_to'"
+	local path_from="$1"
+	local path_subs="$2"
+	local path_to="${path_from#/}"; path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
+	_echoD "${FUNCNAME}() :$LINENO path_from='$path_from' paths_sub='$paths_sub' path_to='$path_to'"
 
 	# wrong path
 	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
@@ -49,6 +47,7 @@ __compress() {
 	_echoT "$PWD"
 
 	for path_sub in $paths_sub; do
+		path_sub=$(echo "$path_sub")
 		if [ -d "$path_sub" ]; then
 			file_to="${path_sub#/}"
 			file_to="${file_to//\//.}"
@@ -58,7 +57,7 @@ __compress() {
 			_evalq "tar $cmd_opt $file_to $path_sub"
 		else
 			_echoE "wrong path '$path_sub'"
-			_echoD "$FUNCNAME:$LINENO wrong path '$path_sub'"
+			_echoD "${FUNCNAME}() :$LINENO wrong path '$path_sub'"
 		fi
 	done
 }
@@ -67,14 +66,14 @@ __bc_conf() {
 	_echoW "conf"
 	path_from="/"
 	paths_sub="boot/grub etc root"
-	_compress "$path_from" "$paths_sub"
+	__compress "$path_from" "$paths_sub"
 }
 
 __bc_scripts() {
 	_echoW "scripts"
 	path_from="/"
 	paths_sub="usr/local/bs"
-	_compress "$path_from" "$paths_sub"
+	__compress "$path_from" "$paths_sub"
 }
 
 __main() {
@@ -87,7 +86,7 @@ __main() {
 	# vz
 	if [ "$vz" ]; then
 		_echoW "launch vz"
-		${S_PATH_SCRIPT}/backup-vz $vz-dump
+		${S_PATH_SCRIPT}/backup-vz ${vzdump}
 	fi
 
 	# kvm
@@ -100,9 +99,10 @@ __main() {
 
 ################################  MAIN
 
-_echoD "$FUNCNAME:$LINENO $_SCRIPT / $(date +"%d-%m-%Y %T : %N") ---- start"
+_echod "---------------------------------------------------------------------"
+_echod "$0 ${FUNCNAME}()"
 
-path_save="$S_PATH_SAVE_BACKUP/$DDATE"
+path_save="$S_PATH_SAVE_BACKUP/$_DDATE"
 cmd_opt=" --exclude='.cache' -czf"
 cmd_ext=tgz
 
@@ -117,7 +117,7 @@ if [ "${_CLUSTER_IPS/$_IPTHIS/}" == "${_CLUSTER_IPS}" ]; then
 	[ "$_ANSWER" == "n" ] && _exit
 fi
 
-_echoD "$FUNCNAME:$LINENO opts_given='$opts_given' opts='$opts'"
+_echoD "${FUNCNAME}() :$LINENO opts_given='$opts_given' opts='$opts'"
 while true; do
 	case "$1" in
 		--help)
@@ -138,7 +138,7 @@ while true; do
 			vz=v
 			;;
 		--vz-dump)
-			vz-dump=--dump
+			vzdump="--dump"
 			;;
 		--kvm)
 			kvm=k
@@ -154,7 +154,7 @@ while true; do
 	shift
 done
 
-_echoD "$FUNCNAME:$LINENO conf='$conf' scripts='$scripts' kvm='$kvm' vz='$vz' \$*='$*'"
+_echoD "${FUNCNAME}() :$LINENO conf='$conf' scripts='$scripts' kvm='$kvm' vz='$vz' \$*='$*'"
 
 __main
 
diff --git a/backup-vz b/backup-vz
--- a/backup-vz
+++ b/backup-vz
@@ -8,9 +8,7 @@
 #S_TRACE=debug
 
 S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
-
-! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
-. "$S_GLOBAL_FUNCTIONS"
+! . "$S_GLOBAL_FUNCTIONS" && echo -e "[error] - Unable to source file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
 
 ################################  VARIABLES
 
@@ -33,10 +31,8 @@ arguments:
 __compress() {
 	local path_from="$1"
 	local path_subs="$2"
-	local path_to
-
-	path_to="${path_from#/}"; path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
-	_echoD "$FUNCNAME:$LINENO path_from='$path_from' path_subs='$path_subs' path_to='$path_to'"
+	local path_to="${path_from#/}"; path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
+	_echoD "${FUNCNAME}() :$LINENO path_from='$path_from' paths_sub='$paths_sub' path_to='$path_to'"
 
 	# wrong path
 	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
@@ -47,20 +43,18 @@ __compress() {
 	cd "$path_from"
 	_echoT "$PWD"
 
-	path_subs=$(echo "$path_subs")
-
-	for path_sub in $path_subs
-	do
+	for path_sub in $paths_sub; do
+		path_sub=$(echo "$path_sub")
 		if [ -d "$path_sub" ]; then
-			file2="${path_sub#/}"
-			file2="${file2//\//.}"
-			file2="$path_to/${file2%/}.$comp_ext"
+			file_to="${path_sub#/}"
+			file_to="${file_to//\//.}"
+			file_to="$path_to/${file_to%/}.$cmd_ext"
 
 			_echo "compress $path_sub"
-			_evalq "tar $comp_opt $file2 $path_sub"
+			_evalq "tar $cmd_opt $file_to $path_sub"
 		else
 			_echoE "wrong path '$path_sub'"
-			_echoD "$FUNCNAME:$LINENO ERROR| Wrong path '$path_sub'"
+			_echoD "${FUNCNAME}() :$LINENO wrong path '$path_sub'"
 		fi
 	done
 }
@@ -76,7 +70,7 @@ __sync() {
 	local path_to="${path_from#/}"
 
 	path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
-	_echoD "$FUNCNAME:$LINENO path_from='$path_from' path_subs='$path_subs' path_to='$path_to'"
+	_echoD "${FUNCNAME}() :$LINENO path_from='$path_from' path_subs='$path_subs' path_to='$path_to'"
 
 	# wrong path
 	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
@@ -87,6 +81,8 @@ __sync() {
 	cd "$path_to"
 	_echoT "$PWD"
 
+	path_subs=$(echo "$path_subs")
+	_echoD "${FUNCNAME}() :$LINENO path_subs='$path_subs'"
 	for path_sub in $path_subs
 	do
 		if [ -d "$path_from/$path_sub" ]; then
@@ -98,7 +94,7 @@ __sync() {
 			_evalq "rsync -a $str $path_from/$path_sub/ $path_sub_to/"
 		else
 			_echoE "wrong path '$path_from/$path_sub'"
-			_echoD "$FUNCNAME:$LINENO ERROR| Wrong path '$path_from/$path_sub'"
+			_echoD "${FUNCNAME}() :$LINENO ERROR| Wrong path '$path_from/$path_sub'"
 		fi
 	done
 }
@@ -155,9 +151,10 @@ __main() {
 
 ################################  MAIN
 
-_echoD "$FUNCNAME:$LINENO $_SCRIPT / $(date +"%d-%m-%Y %T : %N") ---- start"
+_echod "---------------------------------------------------------------------"
+_echod "$0 ${FUNCNAME}()"
 
-path_save="$S_PATH_SAVE_BACKUP/$DDATE/vz"
+path_save="$S_PATH_SAVE_BACKUP/$_DDATE/vz"
 comp_opt=czf
 comp_ext=tgz
 
@@ -167,16 +164,17 @@ opts_long="debug,dump,help,quiet"
 OPTS=$(getopt -o $opts_short -l $opts_long -n "${0##*/}" -- "$@" 2>/tmp/${0##*/}) || _exite "wrong options '$(</tmp/${0##*/})'"
 eval set -- "$OPTS"
 
-_echoD "$FUNCNAME:$LINENO opts_given='$opts_given' OPTS='$OPTS'"
+_echoD "${FUNCNAME}() :$LINENO opts_given='$opts_given' OPTS='$OPTS'"
 while true; do
 	case "$1" in
 		--dump)
 			dump=d
 			;;
-		-h, --help)
-			_echo "$usage"; _exit
+		-h| --help)
+			_echo "$usage"
+			_exit
 			;;
-		-d, --debug)
+		-d| --debug)
 			_redirect debug
 			;;
 		-q|--quiet)
@@ -195,7 +193,7 @@ done
 
 # all options
 # ; log=l
-_echoD "$FUNCNAME:$LINENO conf='$conf' template='$template' dump='$dump' suspend='$suspend' snapshot='$snapshot' share='$share' log='$log'"
+_echoD "${FUNCNAME}() :$LINENO conf='$conf' template='$template' dump='$dump' suspend='$suspend' snapshot='$snapshot' share='$share' log='$log'"
 
 __main
 
diff --git a/inc-lxc b/inc-lxc
--- a/inc-lxc
+++ b/inc-lxc
@@ -7,11 +7,8 @@
 ################################  GLOBAL FUNCTIONS
 #S_TRACE=debug
 
-if [ -z $S_INC_FUNCTIONS ]; then
-	S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
-	! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "error - Unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
-	. "$S_GLOBAL_FUNCTIONS"
-fi
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
+! . "$S_GLOBAL_FUNCTIONS" && echo -e "[error] - Unable to source file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
 
 ################################  CONTAINER
 
diff --git a/lxcinit b/lxcinit
--- a/lxcinit
+++ b/lxcinit
@@ -5,14 +5,11 @@
 # Description:					command to initalize container with options like apache, php-conf, mariadb
 
 ################################ GLOBAL FUNCTIONS
-S_TRACE=debug
+#S_TRACE=debug
 
-if [ -z $S_INC_FUNCTIONS ]; then
-	S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
-	! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "error - Unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
-	. "$S_GLOBAL_FUNCTIONS"
-	. "$S_PATH_SCRIPT/inc-lxc"
-fi
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
+! . "$S_GLOBAL_FUNCTIONS" && echo -e "[error] - Unable to source file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
+! . "$S_PATH_SCRIPT/inc-lxc" && echo -e "[error] - Unable to source file '$S_PATH_SCRIPT/inc-lxc' from '${BASH_SOURCE[0]}'" && exit 1
 
 ################################  VARIABLES
 
@@ -37,8 +34,8 @@ Init usage:    lxcx init <options> [image] [containers]
 ################################  FUNCTION
 
 __common() {
-	_echoD "${FUNCNAME}() IN"
-	_echoD "${FUNCNAME}() S_PATH_INSTALL=${S_PATH_INSTALL} S_PATH_SCRIPT=${S_PATH_SCRIPT}"
+	_echoD "${FUNCNAME}() :$LINENO IN"
+	_echoD "${FUNCNAME}() :$LINENO S_PATH_INSTALL=${S_PATH_INSTALL} S_PATH_SCRIPT=${S_PATH_SCRIPT}"
 
 	# start the container if needed
 	__lxc_is_stopped "$CTNAME" && lxc start "$CTNAME"
@@ -53,7 +50,7 @@ __common() {
 }
 
 __alpine312() {
-	_echoD "${FUNCNAME}() IN"
+	_echoD "${FUNCNAME}() :$LINENO IN"
 
 	local PATH_PROFILE="/etc/profile.d"
 
@@ -71,7 +68,7 @@ __alpine312() {
 }
 
 __buster() {
-	_echoD "${FUNCNAME}() IN"
+	_echoD "${FUNCNAME}() :$LINENO IN"
 
 	# conf
 	lxc file push "${S_PATH_INSTALL_CONF}/.bashrc-lxc-debian" "${CTNAME}/root/.bashrc"
@@ -86,12 +83,12 @@ __buster() {
 }
 
 __focal() {
-	_echoD "${FUNCNAME}() IN"
+	_echoD "${FUNCNAME}() :$LINENO IN"
 
 }
 
 __alpine312_apache() {
-	_echoD "${FUNCNAME}() IN"
+	_echoD "${FUNCNAME}() :$LINENO IN"
 
 	# profile www
 	profile="www"
@@ -127,7 +124,7 @@ __alpine312_apache() {
 }
 
 __alpine312_php() {
-	_echoD "${FUNCNAME}() IN"
+	_echoD "${FUNCNAME}() :$LINENO IN"
 
 	# apache
 	__alpine312_apache
@@ -179,7 +176,7 @@ rc-service apache2 restart && rc-service php-fpm7 restart'
 }
 
 __alpine312_mariadb() {
-	_echoD "${FUNCNAME}() IN"
+	_echoD "${FUNCNAME}() :$LINENO IN"
 
 	# profile sgbd
 	profile="sgbd"
@@ -250,7 +247,7 @@ __main() {
 	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@")
 	eval set -- "${opts}"
 
-	_echoD "${FUNCNAME}() opts_given=$opts_given opts=$opts"
+	_echoD "${FUNCNAME}() :$LINENO opts_given=$opts_given opts=$opts"
 
 	while [ "$1" != "--" ]
 	do
@@ -286,13 +283,13 @@ __main() {
 	IMAGE="$1"
 	IMAGE="${IMAGE/debian10/buster}"
 	IMAGE="${IMAGE/ubuntu2004/focal}"
-	_echoD "${FUNCNAME}() IMAGE='$IMAGE'"
+	_echoD "${FUNCNAME}() :$LINENO IMAGE='$IMAGE'"
 
 	shift
 	# no container name given
 	[ -z "$1" ] && _exite "You have to give a container name to initialize it"
 	CTNAME="$1"
-	_echoD "${FUNCNAME}() CTNAME='$CTNAME'"
+	_echoD "${FUNCNAME}() :$LINENO CTNAME='$CTNAME'"
 
 	# check method are implemented
 	__check
diff --git a/lxcx b/lxcx
--- a/lxcx
+++ b/lxcx
@@ -5,14 +5,11 @@
 # Description:					functions over lxc to manipulate containers
 
 ################################ GLOBAL FUNCTIONS
-S_TRACE=debug
+#S_TRACE=debug
 
-if [ -z $S_INC_FUNCTIONS ]; then
-	S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
-	! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "error - Unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
-	. "$S_GLOBAL_FUNCTIONS"
-	. "$S_PATH_SCRIPT/inc-lxc"
-fi
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
+! . "$S_GLOBAL_FUNCTIONS" && echo -e "[error] - Unable to source file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
+! . "$S_PATH_SCRIPT/inc-lxc" && echo -e "[error] - Unable to source file '$S_PATH_SCRIPT/inc-lxc' from '${BASH_SOURCE[0]}'" && exit 1
 
 ################################  VARIABLES
 
@@ -43,8 +40,8 @@ args:
 # $2 available container names
 __select() {
 	local cts cts_tmp
-	_echoD "${FUNCNAME}() \$1=$1"
-	_echoD "${FUNCNAME}() \$2=$2"
+	_echoD "${FUNCNAME}() :$LINENO \$1=$1"
+	_echoD "${FUNCNAME}() :$LINENO \$2=$2"
 
 	# all
 	if [ "${ALL}" = "all" ]; then
@@ -52,74 +49,74 @@ __select() {
 	else
 		# named containers
 		cts_tmp="$1"
-		#_echoD "${FUNCNAME}() named cts_tmp=${cts_tmp}"
+		#_echoD "${FUNCNAME}() :$LINENO named cts_tmp=${cts_tmp}"
 		# regexped containers
 		for regexp in $REGEXP; do
 			cts_tmp="${cts_tmp} $(lxc list --format=json ${regexp} | jq -r '.[].name' |xargs)"
 		done
-		#_echoD "${FUNCNAME}() all cts_tmp=${cts_tmp}"
+		#_echoD "${FUNCNAME}() :$LINENO all cts_tmp=${cts_tmp}"
 		cts_tmp=`echo ${cts_tmp} | tr " " "\n" | sort -u | xargs`
 		# filters containers
 		for ct in $cts_tmp; do
 			[[ " $2 " = *" $ct "* ]] && cts="${cts} ${ct}"
 		done
 	fi
-	_echoD "${FUNCNAME}() unique cts=${cts}"
+	_echoD "${FUNCNAME}() :$LINENO unique cts=${cts}"
 	echo "$cts"
 }
 
 __start() {
 	local cmd cts cts_selected
-	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
+	_echoD "${FUNCNAME}() :$LINENO \$@=$@"
+	_echoD "${FUNCNAME}() :$LINENO ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
 	cts_selected=`__lxc_list_stopped`
 	cts=`__select "$*" "$cts_selected"`
-	_echoD "${FUNCNAME}() cts=${cts}"
+	_echoD "${FUNCNAME}() :$LINENO cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc start ${cts}"
-		_echoD "${FUNCNAME}() cmd=${cmd}"
+		_echoD "${FUNCNAME}() :$LINENO cmd=${cmd}"
 		$cmd
 	fi
 }
 
 __stop() {
 	local cmd cts cts_selected
-	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
+	_echoD "${FUNCNAME}() :$LINENO \$@=$@"
+	_echoD "${FUNCNAME}() :$LINENO ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
 	cts_selected=`__lxc_list_running`
 	cts=`__select "$*" "$cts_selected"`
-	_echoD "${FUNCNAME}() cts=${cts}"
+	_echoD "${FUNCNAME}() :$LINENO cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc stop ${cts}"
-		_echoD "${FUNCNAME}() cmd=${cmd}"
+		_echoD "${FUNCNAME}() :$LINENO cmd=${cmd}"
 		$cmd
 	fi
 }
 
 __restart() {
 	local cmd cts cts_selected
-	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
+	_echoD "${FUNCNAME}() :$LINENO \$@=$@"
+	_echoD "${FUNCNAME}() :$LINENO ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
 	cts_selected=`__lxc_list_running`
 	cts=`__select "$*" "$cts_selected"`
-	_echoD "${FUNCNAME}() cts=${cts}"
+	_echoD "${FUNCNAME}() :$LINENO cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc restart ${cts}"
-		_echoD "${FUNCNAME}() cmd=${cmd}"
+		_echoD "${FUNCNAME}() :$LINENO cmd=${cmd}"
 		$cmd
 	fi
 }
 
 __delete() {
 	local cmd cts cts_selected
-	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
+	_echoD "${FUNCNAME}() :$LINENO \$@=$@"
+	_echoD "${FUNCNAME}() :$LINENO ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
 	if [ "${FORCE}" ]; then
 		cts_selected=`__lxc_list_existing`
@@ -127,11 +124,11 @@ __delete() {
 		cts_selected=`__lxc_list_stopped`
 	fi
 	cts=`__select "$*" "$cts_selected"`
-	_echoD "${FUNCNAME}() cts=${cts}"
+	_echoD "${FUNCNAME}() :$LINENO cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc delete ${FORCE:+--$FORCE} ${cts}"
-		_echoD "${FUNCNAME}() cmd=${cmd}"
+		_echoD "${FUNCNAME}() :$LINENO cmd=${cmd}"
 		$cmd
 	fi
 }
@@ -147,7 +144,7 @@ __main() {
 	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@")
 	eval set -- "${opts}"
 
-	_echoD "${FUNCNAME}() opts_given=$opts_given opts=$opts"
+	_echoD "${FUNCNAME}() :$LINENO opts_given=$opts_given opts=$opts"
 
 	while [ "$1" != "--" ]
 	do
@@ -181,8 +178,8 @@ __main() {
 
 	action="$1"
 	shift
-	_echoD "${FUNCNAME}() ALL='$ALL' FORCE='$FORCE' REGEXP='$REGEXP' "
-	_echoD "${FUNCNAME}() action='$action'"
+	_echoD "${FUNCNAME}() :$LINENO ALL='$ALL' FORCE='$FORCE' REGEXP='$REGEXP' "
+	_echoD "${FUNCNAME}() :$LINENO action='$action'"
 
 	[ -z "$action" ] && _exite "You have to give an action to execute"
 	if [[ " start stop restart delete " = *" $action "* ]]; then
