replace symbolic links by script

diff --git a/backup-vz b/backup-vz
--- a/backup-vz
+++ b/backup-vz
@@ -1,1 +1,212 @@
-scripts/backup-vz.sh
+#!/bin/bash
+#
+# Provides:             backup-vz
+# Short-Description:    backup vz configuration, dump & templates
+# Description:          backup vz configuration, dump & templates
+
+######################## GLOBAL FUNCTIONS
+#S_TRACE=debug
+
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}"
+! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1
+
+########################  VARIABLES
+
+usage="Usage: backup-vz[arguments]
+backup openvz elements: configuration, logs, dump containers & suspend, snapshot
+with options dump containers before backup
+
+arguments:
+    --dump          	save only vz dumps
+    -c, --clean-log	delete log before backup
+    -h, --help       	show this
+    -q, --quiet      	don't show any infomations except interaction informations
+    -d, --debug    	output in screen & in file debug informations
+"
+
+########################  _SCRIPT
+
+# compress path
+# $1 path base
+# $2 sub path
+__compress() {
+	local path_from="$1"
+	local path_subs="$2"
+	local path_to="${path_from#/}"; path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
+	_echod "${FUNCNAME}::$LINENO path_from='$path_from' paths_sub='$paths_sub' path_to='$path_to'"
+
+	# wrong path
+	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
+
+	# create path
+	! [ -d "$path_to" ] && mkdir -p "$path_to"
+
+	cd "$path_from"
+	_echoT "$PWD"
+
+	for path_sub in $paths_sub; do
+		path_sub=$(echo "$path_sub")
+		if [ -d "$path_sub" ]; then
+			file_to="${path_sub#/}"
+			file_to="${file_to//\//.}"
+			file_to="$path_to/${file_to%/}.$cmd_ext"
+
+			_echo "compress $path_sub"
+			_evalq "tar $cmd_opt $file_to $path_sub"
+		else
+			_echoE "wrong path '$path_sub'"
+			_echod "${FUNCNAME}::$LINENO wrong path '$path_sub'"
+		fi
+	done
+}
+
+# synchronize files
+# $1 path base
+# $2 sub path
+# $3 exclude path
+__sync() {
+	local path_from="$1"
+	local path_subs="$2"
+	local excludes="lost+found $3"
+	local path_to="${path_from#/}"
+
+	path_to="${path_save}/${path_to//\//.}"; path_to="${path_to%/}"
+	_echod "${FUNCNAME}::$LINENO path_from='$path_from' path_subs='$path_subs' path_to='$path_to'"
+
+	# wrong path
+	! [ -d "$path_from" ] && _exite "Wrong path '$path_from' for calling '$*'"
+
+	# create path
+	! [ -d "$path_to" ] && mkdir -p "$path_to"
+
+	cd "$path_to"
+	_echoT "$PWD"
+
+	path_subs=$(echo "$path_subs")
+	_echod "${FUNCNAME}::$LINENO path_subs='$path_subs'"
+	for path_sub in $path_subs
+	do
+		if [ -d "$path_from/$path_sub" ]; then
+			path_sub_to="${path_to}/${path_sub#/}"
+			! [ -d "$path_sub_to" ] && mkdir -p "$path_sub_to"
+
+			str=; for exclude in $excludes; do str+="--exclude='$exclude'"; done
+			_echo "sync $path_sub"
+			_evalq "rsync -a $str $path_from/$path_sub/ $path_sub_to/"
+		else
+			_echoE "wrong path '$path_from/$path_sub'"
+			_echod "${FUNCNAME}::$LINENO ERROR| Wrong path '$path_from/$path_sub'"
+		fi
+	done
+}
+
+__comp_share() {
+	local paths path
+
+	# all paths except mariadb & www
+	paths=`ls "${S_HOST_PATH_SHARE}"|grep -v mariadb|grep -v www`
+	for path in ${paths}; do
+		__compress "${S_HOST_PATH_SHARE}" "${path}"
+	done
+	# for mariadb & www
+	_echoT "STOP CONTAINER FROM 101 to 199"
+	${S_PATH_SCRIPT}/vz-ctl stop 101-199
+	_echoT "Container stopped"
+	for path in www mariadb; do
+		[ -d "${S_HOST_PATH_SHARE}/${path}" ] && __compress "${S_HOST_PATH_SHARE}/${path}" "*"
+	done
+	_echoT "START CONTAINER FROM 101 to 199"
+	${S_PATH_SCRIPT}/vz-ctl start 101-199
+	_echoT "Container started"
+}
+
+__clean_log() {
+	_eval "find ${S_HOST_PATH}/*/var/log/ -name *.gz -exec rm {} \;"
+	_eval "find ${S_HOST_PATH}/*/var/log/ -name *.1 -exec rm {} \;"
+}
+
+__main() {
+
+	# clean log
+	[ "${clean_log}" ] && __clean_log
+
+	# dump all containers, force to stop if not
+	if [ "$dump" ]; then
+		_echoT "force dumping to each containers"
+		${S_PATH_SCRIPT}/vz-dump -cyf 101-199
+	fi
+
+	# conf
+	__compress "/" "etc/vz etc root/.ssh root"
+
+	# log
+	__compress "$S_VZ_PATH_NODE" "*/log"
+
+	# dump
+	__sync "$S_HOST_PATH" "dump" "/suspend /snapshot /template"
+
+	# template
+	__sync "$S_VZ_PATH_DUMP" "template"
+
+	# suspend
+	__sync "$S_VZ_PATH_DUMP" "suspend"
+
+	# snapshot
+	__sync "$S_VZ_PATH_DUMP" "snapshot"
+
+	# share
+	__comp_share
+}
+
+########################  MAIN
+
+_echod "======================================================"
+_echod "$(ps -o args= $PPID)"
+
+path_save="$S_PATH_BACKUP/$_DATE/vz"
+comp_opt=czf
+comp_ext=tgz
+
+opts_given="$@"
+opts_short="dchq"
+opts_long="dump,clean-log,debug,help,quiet"
+OPTS=$(getopt -o $opts_short -l $opts_long -n "${0##*/}" -- "$@" 2>/tmp/${0##*/}) || _exite "wrong options '$(</tmp/${0##*/})'"
+eval set -- "$OPTS"
+
+_echod "${FUNCNAME}::$LINENO opts_given='$opts_given' OPTS='$OPTS'"
+while true; do
+	case "$1" in
+		--dump)
+			dump=true
+			;;
+		-h| --help)
+			_echo "$usage"
+			_exit
+			;;
+		-c| --clean-log)
+			clean_log=true
+			;;
+		-d| --debug)
+			_redirect debug
+			;;
+		-q|--quiet)
+			_redirect quiet
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			_exite "Bad options: '$1' in '$opts_given'"
+			;;
+	esac
+	shift
+done
+
+# all options
+# ; log=l
+_echod "${FUNCNAME}::$LINENO conf='$conf' template='$template' dump='$dump' suspend='$suspend' snapshot='$snapshot' share='$share' log='$log'"
+
+__main
+
+_exit 0
diff --git a/haconf b/haconf
--- a/haconf
+++ b/haconf
@@ -1,1 +1,257 @@
-scripts/haconf.sh
+#!/bin/bash
+#
+# Provides:             haconf
+# Short-Description:    control extended configurations files for haproxy
+# Description:          control extended configurations files for haproxy
+
+######################## GLOBAL FUNCTIONS
+#S_TRACE=debug
+
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}"
+! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1
+
+########################  VARIABLES
+
+usage="haconf, control extended configurations files for haproxy
+haconf -h, --help
+
+For the optionnal arguments NAME, you can use the wildcard for the name
+	or alone for all selection.
+	without agument NAME command return a global selection without filter.
+
+options:
+    -h, --help			print usage of this command
+    -q, --quiet		Don't show any infomations except errors
+    -d, --debug		output debugging in screen & file
+
+	check				check all the enabled configuration files
+	reload				reload the haproxy daemon
+
+    clear						clear all broken links of configurations
+    list <names>			return a list of 'enabled / disabled / broken' configurations
+    enable <names>	enable disabled configuration names
+    								& print a list of 'enabled / enable' configurations
+    disable <names>	disable an enabled configuration
+    								& print a list of 'disabled / enable' configurations
+    <names> are an expansion format
+"
+
+########################  FUNCTION
+
+# check enabled configuration files
+__check() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local configs conf
+	configs=
+
+	for conf in $(ls ${path_enabled}/* 2>/dev/null); do
+		configs+=" -f ${conf}"
+	done;
+
+	if msg=`haproxy -c -f /etc/haproxy/haproxy.cfg ${configs} 2>&1`; then
+		_echo 'OK'
+	else
+		_echoE 'KO'
+		_echo "${msg}"
+		_exit 1
+	fi
+}
+
+# clear broken links for names of available configuration
+__clear() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local confs
+
+	confs="$(find -L ${path_enabled}/ -type l|sort|sed "s|${path_enabled}/||")"
+	_evalq "find -L ${path_enabled}/ -type l -exec rm {} \\;"
+
+	[ "$confs" ] && _echo "The following broken links are deleted:\n$confs"
+}
+
+__print() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local conf enabled disabled
+
+	# enabled
+	enabled="$(find -L ${path_enabled}/ -type f|sort|sed "s|${path_enabled}/||")"
+
+	# disabled
+	disabled="$(ls "${path_available}")"
+    for conf in ${enabled}; do
+    	disabled="${disabled/$conf}"
+    done
+	disabled="$(echo -e "${disabled}"|sort -u|sed '/^$/d')"
+	_echod "${FUNCNAME}::${LINENO} enabled=${enabled}"
+	_echod "${FUNCNAME}::${LINENO} disabled=${disabled}"
+
+	#paste <(echo -e "--${1}--\n${ok}") <(echo -e "--enabled--\n${enabled}") <(echo -e "--disabled--\n${disabled}")|column -tn
+	#[ "${ok}" ] && echo -e "\nTo activate the new configuration, use 'haconf reload'"
+	echo -e "${1}  \t"${ok%\\n}
+	echo -e "enabled \t"${enabled}
+	echo -e "disabled\t"${disabled}
+	[ "${ok}" ] && echo -e "\nTo activate the new configuration, use 'haconf reload'"
+}
+
+# 1 path to list
+# s-@ names to search
+__get_confs() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local path confs conf
+	path="$1"
+	shift
+	_echod "${FUNCNAME}::${LINENO} path=${path} \$@=$@"
+
+	# list confs
+	for conf in $@; do
+		confs="${confs}
+$(ls -1 "${path}"/${conf} 2>/dev/null)"
+	done
+	echo -e "$confs"|sort -u|sed "s|${path}/||"|xargs
+}
+
+# enable configuration files with his short names (without extension)
+# $* : configuration names
+__enable() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local conf confs enabled ok ko
+
+	confs="$(__get_confs "${path_available}" "$@")"
+	_echod "${FUNCNAME}::${LINENO} confs="${confs}
+
+	# select confs
+	for conf in ${confs}; do
+	    [ -h "${path_enabled}/${conf}" ]  && _evalq rm "${path_enabled}/${conf}"
+	    _evalq ln -s ${path_available}/${conf} ${path_enabled}/${conf}
+	    ok="${ok}${conf}\n"
+	done
+
+	__print "enable "
+}
+
+# disable configuration files with his short names (without extension)
+# $* : configuration names
+__disable() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local conf confs enabled ok ko
+
+	confs="$(__get_confs "${path_available}" "$@")"
+	_echod "${FUNCNAME}::${LINENO} confs="${confs}
+
+	# select confs
+	for conf in ${confs}; do
+		if [ -e "${path_enabled}/${conf}" ]; then
+			_evalq rm ${path_enabled}/${conf}
+			ok="${ok}${conf}\n"
+		fi
+	done
+
+	__print "disable"
+}
+
+# print list names of available configuration
+__list() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	local enabled disabled ko conf
+
+	# select confs
+	if [ -z $@ ]; then
+		disabled="$(ls "${path_available}")"
+		enabled="$(find -L "${path_enabled}"/ -type f|sort|sed "s|${path_enabled}/||")"
+		ko="$(find -L "${path_enabled}"/ -type l|sort|sed "s|${path_enabled}/||")"
+	else
+		# select confs
+		for conf in $@; do
+			disabled+="\n$(find ${path_available}/ -type f -name ${conf}|sort|sed "s|${path_available}/||")"
+			enabled+="\n$(find -L ${path_enabled}/ -type f -name ${conf}|sort|sed "s|${path_enabled}/||")"
+			ko+="\n$(find -L ${path_enabled}/ -type l -name ${conf}|sort|sed "s|${path_enabled}/||")"
+		done
+	fi
+
+	# disabled
+    for conf in ${enabled}; do
+    	disabled="${disabled/$conf}"
+    done
+	disabled="$(echo -e "${disabled}"|sort -u|sed '/^$/d')"
+	enabled="$(echo -e "${enabled}"|sort -u|sed '/^$/d')"
+	ko="$(echo -e "${ko}"|sort -u|sed '/^$/d')"
+
+	echo -e "enabled \t"${enabled}
+	echo -e "disabled\t"${disabled}
+	[ "${ko}" ] && echo -e "broken  \t"${ko} && echo -e "\nTo clean broken links, use: 'haconf clear'"
+}
+
+# reload haproxy daemon
+__reload() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	_service reload haproxy && _echo "haproxy have been reloaded" || _echoE "error, something wrong"
+}
+
+__opts() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	opts_short="hdq"
+	opts_long="help,debug,quiet"
+	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@") || _exite "Wrong or missing options"
+	eval set -- "${opts}"
+
+	_echod "${FUNCNAME}::${LINENO} opts=${opts}"
+	while [ "$1" != "--" ]; do
+		case "$1" in
+			--help)
+				echo "${usage}" && exit
+				;;
+			-q|--quiet)
+				_redirect quiet
+				;;
+			-d|--debug)
+				_redirect debug
+				;;
+		esac
+		shift
+	done
+
+	shift
+	action="$1"
+	shift
+	opts="$@"
+	_echod "${FUNCNAME}::${LINENO} action='${action}' opts='${opts}'"
+}
+
+__main() {
+	_echod "======================================================"
+	_echod "$(ps -o args= $PPID)"
+	local opts_short opts_long opts
+	local path_available path_enabled path
+	path_enabled="/etc/haproxy/conf-enabled"
+	path_available="/etc/haproxy/conf-available"
+
+	! type haproxy &>/dev/null && _exite "Haproxy are not installed !"
+
+	for path in "${path_enabled}" "${path_available}"; do
+		! [ -d "${path}" ] && mkdir -p "${path}"
+	done
+
+	__opts "$@"
+
+	[ -z "${action}" ] && _exite "You have to give an action to execute"
+	if ! [ -d "${path_available}" ] || ! [ -d "${path_enabled}" ]; then _exite "Unable to find path ${path_available} or ${path_enabled}"; fi
+
+	if [[ " check clear enable disable list reload " = *" $action "* ]]; then
+		# call action with arguments
+		__$action "${opts}"
+	else
+		_exite "Wrong action: '$action'. select in: check clear enable disable list reload"
+	fi
+}
+
+########################  MAIN
+
+__main "$@"
diff --git a/rsync-lxd b/rsync-lxd
--- a/rsync-lxd
+++ b/rsync-lxd
@@ -1,1 +1,117 @@
-scripts/rsync-lxd.sh
+#!/bin/bash
+#
+# sync install bs & install path to LXD containers
+
+
+######################## GLOBAL FUNCTIONS
+#S_TRACE=debug
+
+S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}"
+! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1
+
+########################  VARIABLES
+
+usage="rsync-lxd, sync files between host and LXD containers
+rsync-lxd -h, --help
+
+options:
+    -h, --help		Print usage of this command
+    -v, --verbose		Print details of files transfer
+    -p, --create-dirs   Create any directories necessary
+    -r, --recursive	Recursively transfer files
+    -d, --delete	Delete files before pushing
+
+    --publish		publish container fater sync
+
+    --bs		sync only the path ${S_PATH_SCRIPT}
+    --install		sync only the path ${S_PATH_INSTALL}
+"
+
+########################  FUNCTION
+
+# check enabled configuration files
+__push() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+	local path path_to path_from path_tmp ct
+
+	# path
+	paths_sel="${paths_sel:-${S_PATH_SCRIPT}}"
+
+	# cts_sel
+	cts_sel="${cts_sel:-`lxc list -f csv -c n status=Running`}"
+
+	for path in ${paths_sel}; do
+
+		path_to="${path//${S_PATH_INSTALL}/\/usr/\local\/install}" # for desktop host
+		path="${path//-desktop/}" # for desktop host
+
+		path_from="/tmp/${path##*/}"
+		[ -d "${path_from}" ] && _eval rm -fR ${path_from}
+		_eval cp -a ${path} ${path_from}
+		[ -d "${path_from}/.git" ] && _eval rm -fR "${path_from}/.git"
+
+		for ct in ${cts_sel}; do
+			_echo "${path} -> ${ct}"
+
+			[ "${delete}" ] && _lxc_exec ${ct} "[ -d ${path_to} ] && rm -fR ${path_to}"
+			_eval lxc file push ${args} ${path_from} $ct${path_to%/*}
+		done
+	done
+}
+
+__publish() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+	local ct
+
+	for ct in ${cts_sel}; do
+		_echo "publish - ${ct}"
+		# rename
+		lxc image list -f csv -c l | grep -q ^${ct}$ && _eval lxc image alias rename ${ct} ${ct}-${_SDATE}
+		_eval lxc publish --force ${ct} --alias ${ct}
+	done
+}
+
+__opts() {
+	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
+
+	opts_short="hvrpd"
+	opts_long="help,verbose,recursive,create-dirs,delete,publish,bs,install"
+	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@") || _exit 1
+	eval set -- ${opts}
+	_echod "${FUNCNAME}::${LINENO} opts=${*}"
+
+	args=" --quiet"
+	while [ "$1" != "--" ]; do
+		case "$1" in
+			-h|--help)			echo "${usage}" && exit ;;
+			-v|--verbose)		args="${args/ --quiet/}"  ;;
+			-r|--recursive)		args+=" --recursive"  ;;
+			-p|--create-dirs)	args+=" --create-dirs"  ;;
+			-d|--delete)			delete=y  ;;
+			--publish)			publish=y  ;;
+			--bs)						paths_sel+=" ${S_PATH_SCRIPT}"  ;;
+			--install)				paths_sel+=" ${S_PATH_INSTALL}"  ;;
+		esac
+		shift
+	done
+	shift
+	cts_sel=$*
+	_echod "${FUNCNAME}::${LINENO} cts_sel=${cts_sel}"
+}
+
+__main() {
+	_echod "======================================================"
+	_echod "$(ps -o args= $PPID)"
+	local opts_short opts_long opts
+	local paths_sel args delete cts_sel
+
+	! type lxc >/dev/null 2>&1 && _exite "LXC command not found !"
+
+	__opts "$@"
+	__push
+	[ "${publish}" ] && __publish
+}
+
+########################  MAIN
+
+__main "$@"
