Replace all variables named path by pth for compatibility with zsh...

diff --git a/clean-pkg b/clean-pkg
--- a/clean-pkg
+++ b/clean-pkg
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# command get short from to list $path_pkg
-# command to list $path_pkg
+# command get short from to list $pth_pkg
+# command to list $pth_pkg
 __filter() {
 	echo -n "filter ${NUM}: "
 	NUM=$((${NUM} + 1))
@@ -26,9 +26,9 @@ __filter() {
 
 ########################  MAIN
 
-[ -d /var/cache/pacman/pkg ] && path_pkg=/var/cache/pacman/pkg && os=manajro
-[ -d /var/cache/apt/archives ] && path_pkg=/var/cache/apt/archives && os=ubuntu
-[ "${path_pkg}" ] || echo "[error]${FUNCNAME}:${LINENO} Unable to find a path"
+[ -d /var/cache/pacman/pkg ] && pth_pkg=/var/cache/pacman/pkg && os=manajro
+[ -d /var/cache/apt/archives ] && pth_pkg=/var/cache/apt/archives && os=ubuntu
+[ "${pth_pkg}" ] || echo "[error]${FUNCNAME}:${LINENO} Unable to find a path"
 
 [ "${USER}" != "root" ] && sudo="sudo"
 files_log="/var/log/server/clean-pkg.info"
@@ -38,10 +38,10 @@ files_del="/tmp/pkg-del"
 
 NUM=1
 
-__filter "ls -1 ${path_pkg}|grep zst\$|sed 's|^\(.*\)-[0-9\.]\+-[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${path_pkg}/\${short}-[0-9]*.zst|tail -n +2"
-__filter "ls -1 ${path_pkg}|grep zst\$|sed 's|^\([a-z0-9-]\+\)-[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${path_pkg}/\${short}-[0-9]*.zst|tail -n +2"
-__filter "ls -1 ${path_pkg}|grep zst\$|sed 's|^\(.*\)-[0-9\.]\+-[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${path_pkg}/\${short}-[0-9]*.zst|tail -n +2"
-__filter "ls -1 ${path_pkg}|grep zst\$|sed 's|^\(.*\)-[0-9]:[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${path_pkg}/\${short}-[0-9]:[0-9]*.zst|tail -n +2"
+__filter "ls -1 ${pth_pkg}|grep zst\$|sed 's|^\(.*\)-[0-9\.]\+-[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${pth_pkg}/\${short}-[0-9]*.zst|tail -n +2"
+__filter "ls -1 ${pth_pkg}|grep zst\$|sed 's|^\([a-z0-9-]\+\)-[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${pth_pkg}/\${short}-[0-9]*.zst|tail -n +2"
+__filter "ls -1 ${pth_pkg}|grep zst\$|sed 's|^\(.*\)-[0-9\.]\+-[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${pth_pkg}/\${short}-[0-9]*.zst|tail -n +2"
+__filter "ls -1 ${pth_pkg}|grep zst\$|sed 's|^\(.*\)-[0-9]:[0-9].*|\1|'|grep -v zst|sort -ur" "ls -r1 ${pth_pkg}/\${short}-[0-9]:[0-9]*.zst|tail -n +2"
 
 exit
 
diff --git a/gists b/gists
--- a/gists
+++ b/gists
@@ -34,8 +34,8 @@ __valid() {
 }
 
 __clone() {
-	path_in=$(pwd)
-	cd "${path_gists}"
+	pth_in=$(pwd)
+	cd "${pth_gists}"
 
 	while read i n; do
 		echo "- ${n} ${i}"
@@ -46,24 +46,24 @@ __clone() {
 		fi
 	done <<<${gists}
 
-	cd ${path_in}
+	cd ${pth_in}
 }
 
 __cmd() {
-	path_in=$(pwd)
+	pth_in=$(pwd)
 
 	while read id name; do
-		path="${path_gists}/${name}:${id}"
-		if ! [ -d "${path}" ]; then
+		pth="${pth_gists}/${name}:${id}"
+		if ! [ -d "${pth}" ]; then
 			echo -e "${red}- ${name} missing \nUse 'gists clone ${id}'${cclear}"
 			continue
 		fi
-		cd "${path_gists}/${name}:${id}"
+		cd "${pth_gists}/${name}:${id}"
 		echo -e "${yellow}- ${name} ${id}${cclear}"
 		git $*
 	done <<<${gists}
 
-	cd ${path_in}
+	cd ${pth_in}
 }
 
 __list() {
@@ -71,23 +71,23 @@ __list() {
 }
 
 __purge() {
-	path_in=$(pwd)
-	cd "${path_gists}" 
+	pth_in=$(pwd)
+	cd "${pth_gists}" 
 
-	paths=
-	while read path; do
-		if ! echo "${gists}" | grep -q "${path##*:} ${path%%:*}"; then
-			paths+="${path} "
+	pths=
+	while read pth; do
+		if ! echo "${gists}" | grep -q "${pth##*:} ${pth%%:*}"; then
+			pths+="${pth} "
 		fi
 	done <<< $( ls )
-	if [ "${paths}" ]; then
+	if [ "${pths}" ]; then
 		echo "Confirm following deletions:"
-		echo ${paths} | tr ' ' '\n'
+		echo ${pths} | tr ' ' '\n'
 		read -p "Y/n: " _ANSWER
-		[ -z "${_ANSWER/y/}" ] && rm -fR ${paths}
+		[ -z "${_ANSWER/y/}" ] && rm -fR ${pths}
 	fi
 
-	cd ${path_in}
+	cd ${pth_in}
 }
 
 __init() {
@@ -103,8 +103,8 @@ __init() {
 	token=$(grep '^# gist' $tokenfile -A1|sed 1d)
 	[ -z "${token}" ] && echo "Unable to find token in file: '${tokenfile}'" && exit 1
 	# gists path
-	path_gists=${HOME}/repo/gists
-	! [ -d "${path_gists}" ] && echo "Unable to find gists path: '${path_gists}'" && exit 1
+	pth_gists=${HOME}/repo/gists
+	! [ -d "${pth_gists}" ] && echo "Unable to find gists path: '${pth_gists}'" && exit 1
 	# initialize gists
 	gists=
 
