bs/inc-functions : modification of configuration for /etc/server.conf loading

diff --git a/inc-functions b/inc-functions
--- a/inc-functions
+++ b/inc-functions
@@ -94,7 +94,7 @@ _askyn() {
 _asks() {
 	_ANSWER=
 	shift
-	[ -z "$*" ] && _exitE "invalid options '$*' for _asks()"
+	[ -z "$*" ] && _exite "invalid options '$*' for _asks()"
 	options="$*"
 	while [ "${options/$_ANSWER/}" = "$options" ]; do
 		_echo- -n "$1: "
@@ -170,7 +170,7 @@ _exit() {
 	[ "$*" ] && exit $* || exit
 }
 # exit, with default error 1
-_exitE() {
+_exite() {
 	[ "$1" ] && _echoE "$1" || _echoE "error - ${_SCRIPTFILE}"
 	_echoD "exit - $*"
 	[ "$2" ] && exit $2 || exit 1
@@ -180,9 +180,9 @@ _exitE() {
 
 _source() {
 	local file
-	[ -z "$*" ] && _exitE "unable to source nothing"
+	[ -z "$*" ] && _exite "unable to source nothing"
 	for file in $*; do
-		! [ -f "$file" ]  && _exitE "unable to source '$file'"
+		! [ -f "$file" ]  && _exite "unable to source '$file'"
 		_echoD "_source '$file'"
 		. "$file"
 	done
@@ -191,9 +191,9 @@ _source() {
 }
 _require() {
 	local file
-	[ -z "$*" ] && _exitE "unable to source nothing"
+	[ -z "$*" ] && _exite "unable to source nothing"
 	for file in $*; do
-		! [ -f "$file" ] && _exitE "unable to find '$file'"
+		! [ -f "$file" ] && _exite "unable to find '$file'"
 	done
 }
 
@@ -213,7 +213,7 @@ _keepmvts() {
 _confhave() {
 	local file
 	file="${2:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 	grep -q "^$1=.*" "$file"
 }
 # 1 array name
@@ -222,7 +222,7 @@ _confhave() {
 _confhave_array() {
 	local file
 	file="${3:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 	grep -q "^${1}\['${2}'\]=.*" "$file"
 }
 # 1 variable name
@@ -230,7 +230,7 @@ _confhave_array() {
 _confget() {
 	local file
 	file="${2:-$S_FILE_INSTALL_CONF}"file=
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 
 	_confhave "$1" "$file" && sed -n "s|^${1}=||p" $file | sed 's/"//g'
 }
@@ -240,7 +240,7 @@ _confget() {
 _confset() {
 	local file
 	file="${3:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 
 	if _confhave "$1" "$file"; then
 		sed -i "\|^$1=| c${1}=${2:+\"$2\"}" "$file"
@@ -255,7 +255,7 @@ _confset() {
 _confset_array() {
 	local file
 	file="${4:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 
 	if _confhave_array "$1" "$2" "$file"; then
 		sed -i "\|^${1}\['${2}'\]=| c${1}\['${2}'\]=${3:+\"$3\"}" "$file"
@@ -269,7 +269,7 @@ _confset_array() {
 _confmulti_havevalue() {
 	local file
 	file="${3:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 
 	[[ " $(_confget "$1" "$file") " = *" $2 "* ]]
 }
@@ -279,7 +279,7 @@ _confmulti_havevalue() {
 _confmulti_add() {
 	local file str
 	file="${3:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 
 	_confmulti_havevalue "$1" "$2" "$file" && return 0
 	str="$(tr ' ' '\n' <<<"$(_confget "$1" "$file") $2" | sort | xargs)"
@@ -291,7 +291,7 @@ _confmulti_add() {
 _confmulti_remove() {
 	local file str
 	file="${3:-$S_FILE_INSTALL_CONF}"
-	! [ -f "$file" ] && _exitE "unable to find '$file' from $FUNCNAME"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
 
 	_confmulti_havevalue "$1" "$2" "$file" || return 0
 	str=`sed "y/ /\n/;s/^${2}$//M" <<<"$(_confget "$1" "$file")" | xargs`
@@ -320,7 +320,7 @@ _get_ip() {
 	local interface
 	interface="${1:-$(ip -4 -o route show to default|cut -d' ' -f5)}"
 	#ifconfig $inter | sed -n 's|^\s\+inet \(addr:\)\?\([0-9\.]\+\) .*|\2|p'
-	[ "${interface}" ] && ip -4 -o address show dev ${interface}|sed 's|.*inet\s\([0-9\.]\+\)/.*|\1|'
+	[ "${interface}" ] && ip -br -4 -o address show dev ${interface}|sed 's|.*\s\+\([0-9\.]\+\)/.*|\1|'
 	# for ip version >= ss190107, with -j option
 	#interface=`ip -4 -j route show to default|jq -r '.[0].dev'`
 	#ip -4 -j address show dev ${interface}|jq -r '.[].addr_info[0].local|select(.!=null)'
@@ -330,7 +330,7 @@ _get_ipv6() {
 	local interface
 	interface="${1:-$(ip -6 -o route show to default|cut -d' ' -f5)}"
 	#ifconfig ${interface} | sed -n 's|^\s\+inet6 \(addr:\)\?\([0-9a-z\:]\+\) .*128.*|\2|p'
-	[ "${interface}" ] && ip -6 -o address show dev ${interface}|sed -n 's|.*inet6\s\([0-9a-z:.]\+\)/128.*|\1|p'
+	[ "${interface}" ] && ip -br -6 -o address show dev ${interface}|sed 's|.*\s\+\([0-9a-z:]\+\)/128.*|\1|'
 	# for ip version >= ss190107, with -j option
 	#ip -6 -j address show dev ${interface}|jq -r '.[].addr_info[0].local|select(.!=null)'
 }
@@ -342,14 +342,14 @@ _get_ipv6() {
 # $2 service
 _service() {
 	# wrong number of parameters
-	[ "$#" -lt 2 ] && _exitE "$FUNCNAME:$LINENO Internal error, missing parameters: '$#'"
+	[ "$#" -lt 2 ] && _exite "$FUNCNAME:$LINENO Internal error, missing parameters: '$#'"
 
     if type systemctl >/dev/null 2>&1; then
 		_evalq systemctl "${1}" "${2}.service"
     elif type service >/dev/null 2>&1; then
         _evalq service "${2%.*}" "${1}"
     else
-        _exitE "unable to load service"
+        _exite "unable to load service"
     fi
 }
 
@@ -361,7 +361,7 @@ _service() {
 _var_unset() {
 	local values value
 	# wrong parameters number
-	[ "$#" -lt 2 ] && _exitE "$FUNCNAME:$LINENO Internal error, wrong parameters numbers (2): '$#'"
+	[ "$#" -lt 2 ] && _exite "$FUNCNAME:$LINENO Internal error, wrong parameters numbers (2): '$#'"
 
 	case "$1" in
 		part)
@@ -371,7 +371,7 @@ _var_unset() {
 			[ "$*" != "*" ] && values="$(set -o posix; set|grep '^S_[a-zA-Z09_-]\+' -o)"
 			;;
 		*)
-		_exitE "Bad options: '$1' in '$*'"
+		_exite "Bad options: '$1' in '$*'"
 		;;
 	esac
 
@@ -384,7 +384,7 @@ _var_unset() {
 _var_replace_www() {
 	local strs str
 	# wrong parameters number
-	[ "$#" -lt 1 ] && _exitE "$FUNCNAME:$LINENO Internal error, wrong parameters numbers (1): '$#'"
+	[ "$#" -lt 1 ] && _exite "$FUNCNAME:$LINENO Internal error, wrong parameters numbers (1): '$#'"
 
 	strs="_MYDOMAIN _SUBDOMAIN _PATH_WWW S_LOG_IPV4 S_RSYSLOG_PTC S_RSYSLOG_PORT S_PATH_LOG S_HOSTING_PATH_LOG S_HOST_IPV6"
 	for str in $strs; do
@@ -400,7 +400,7 @@ _var_replace_www() {
 
 _var_replace() {
 	local strs str
-	[ "$#" -lt 1 ] && _exitE "$FUNCNAME:$LINENO Internal error, wrong parameters numbers (1): '$#'"
+	[ "$#" -lt 1 ] && _exite "$FUNCNAME:$LINENO Internal error, wrong parameters numbers (1): '$#'"
 
 	strs="_MYDOMAIN _SUBDOMAIN _PATH_WWW S_LOG_IPV4 S_RSYSLOG_PTC S_RSYSLOG_PORT S_PATH_LOG S_HOSTING_PATH_LOG _VM_IP_BASE S_HOST_IPV4 S_HOST_IPV6"
 	for str in $strs; do
@@ -447,7 +447,7 @@ _vz_ctids_clean()
 _vz_ctids_inter() {
 	local ctids ctid
 
-	[ $# != 2 ] && _exitE "$FUNCNAME:$LINENO missing arguments $#"
+	[ $# != 2 ] && _exite "$FUNCNAME:$LINENO missing arguments $#"
 	for ctid in $2; do
 		[[ " $1 " = *" $ctid "* ]] && ctids+="$ctid "
 	done
@@ -525,7 +525,7 @@ _redirect() {
 		#			2										1						4						5				6
 		quiet)		exec 2> >(tee -a "$f_err" "$f_info")	1>&						4>>"$f_info"			5>>"$f_info"	6>/dev/null				;;
 		info)		exec 2> >(tee -a "$f_err" "$f_info")	1> >(tee -a "$f_info")	4> >(tee -a "$f_debug")	5>>"$f_info"	6>/dev/null				;;
-		verbose)	exec 2> >(tee -a "$f_err" "$f_info")	1> >(tee -a "$f_info")	4>&1					5>&1			6>/dev/null				;;
+		verbose)	exec 2> >(tee -a "$f_err" "$f_info")	1> >(tee -a "$f_info")	4>&1					5>&1			6>>"$f_debug"			;;
 		debug)		exec 2> >(tee -a "$f_err" "$f_info")	1> >(tee -a "$f_info")	4>&1					5>&1			6> >(tee -a "$f_debug")	;;
 	esac
 }
@@ -546,7 +546,9 @@ SDATE=`date +%s` # date for keeping file
 if [[ -z "$S_GLOBAL_CONF" || ! -f "$S_GLOBAL_CONF" ]]; then
 	echo -e "${red}alert - value of \$S_GLOBAL_CONF are empty from ${BASH_SOURCE[0]}${cclear}"
 	file="${_PATH_BASE}/conf-init.install"
-	if ! . "$file"; then echo -e "${redb}error - unable to find file '$file' from ${BASH_SOURCE[0]}${cclear}" && exit 1; fi
+	if ! . "$file"; then
+		if ! . /etc/server/server.conf; then echo -e "${redb}error - unable to find file '$file' from ${BASH_SOURCE[0]}${cclear}" && exit 1; fi
+	fi
 fi
 . "$S_GLOBAL_CONF"
 
@@ -558,8 +560,8 @@ S_FILE_INSTALL_CONF="${S_PATH_CONF}/install.conf"
 
 _CLUSTER_IPS=`sed 'y/ /\n/' <<<${S_CLUSTER[*]} | sed -n 's/^ip=\([^ ]\?\)/\1/p' | xargs`
 _IPS_AUTH=`printf "%q\n" ${S_IPS_ADMIN} ${S_IPS_DEV} | sort -u | xargs`
-_IPTHIS=`_get_ip`
-_IPTHISV6=`_get_ipv6`
+[ ${S_SERVER_TYPE} = 'vz' ] && _IPTHIS=`_get_ip ${S_ETH}` || _IPTHIS=`_get_ip`
+[ ${S_SERVER_TYPE} = 'vz' ] || _IPTHISV6=`_get_ipv6`
 if [[ " lxc vz docker " = *" $S_SERVER_TYPE "* ]]; then
 	_VM_IP_BASE="${_IPTHIS%.*}}"
 else
