lxc: major modification of lxcx add lxcinit to intialiaze new container from image add inc-lxc to add some elmentariesy functions

diff --git a/inc-functions b/inc-functions
--- a/inc-functions
+++ b/inc-functions
@@ -14,54 +14,72 @@ _echo() {
 _echo-() {
 	echo -e $* >&4
 }
+_echod() {
+	_echoD "$*"
+	echo -e "$(date +"%Y%m%d %T") $*" >> "${_SF_INF}"
+}
 
 # debug
 _echoD() {
-	echo "$(date +"%Y%m%d-%H%M%S") $*" >&6
+	echo "$(date +"%Y%m%d %T") $*" >&6
 }
 # error
 _echoe() {
-	_echoD "error - $*"
-	echo -e "error - ${red}${*}${cclear}" >&2
+	_echoD "[error] $*"
+	echo -e "[error] ${red}${*}${cclear}" >&2
 }
 _echoE() {
-	_echoD "error - $*"
-	echo -e "error - ${redb}${*}${cclear}" >&2
+	_echoD "[error] $*"
+	echo -e "[error] ${redb}${*}${cclear}" >&2
 }
 
 # information
 _echoi() {
-	_echoD "info - $*"
+	_echoD "[info] $*"
 	echo -e "${yellow}${*}${cclear}" >&4
 }
 _echoI() {
-	_echoD "info - $*"
+	_echoD "[info] $*"
 	echo -e "${yellowb}${*}${cclear}" >&4
 }
 
 # title
 _echot() {
-	_echoD "title - $*"
+	_echoD "[title] $*"
 	echo -e "${blue}${*}${cclear}" >&4
 }
 _echoT() {
-	_echoD "title - $*"
+	_echoD "[title] $*"
 	echo -e "${blueb}${*}${cclear}" >&4
 }
 
 # alert
 _echoa() {
-	_echoD "alert - $*"
+	_echoD "[alert] $*"
 	echo -e "${magenta}${*}${cclear}" >&4
 }
 _echoA() {
-	_echoD "alert - $*"
+	_echoD "[alert] $*"
 	echo -e "${magentab}${*}${cclear}" >&4
 }
 
 # echo white bold
 _echoW() {
 	echo -e "${whiteb}${*}${cclear}" >&4
+}
+
+##############  EXIT
+
+# exit
+_exit() {
+	_echoD "exit - $*"
+	[ "$*" ] && exit $* || exit
+}
+# exit, with default error 1
+_exite() {
+	[ "$1" ] && _echoE "$1" || _echoE "error - ${_SCRIPTFILE}"
+	_echoD "exit - $*"
+	[ "$2" ] && exit $2 || exit 1
 }
 
 ##############  ASK
@@ -147,26 +165,12 @@ _menur() {
 ##############  EVAL
 
 _eval() {
-	_echoD "eval $*"
+	_echoD "${FUNCNAME}() $*"
 	eval $* >&1
 }
 _evalq() {
-	_echoD "evalq $*"
+	_echoD "${FUNCNAME}() $*"
 	eval $* >&4
-}
-
-##############  EXIT
-
-# exit
-_exit() {
-	_echoD "exit - $*"
-	[ "$*" ] && exit $* || exit
-}
-# exit, with default error 1
-_exite() {
-	[ "$1" ] && _echoE "$1" || _echoE "error - ${_SCRIPTFILE}"
-	_echoD "exit - $*"
-	[ "$2" ] && exit $2 || exit 1
 }
 
 ##############  SOURCE
@@ -498,6 +502,7 @@ _reenter() {
 ##############  REDIRECT
 
 _redirect() {
+	local opt
 
 	# return if fd are already open
 	[[ `_fd_io 4` = "0"* ]] && return 1
@@ -508,24 +513,27 @@ _redirect() {
 	fi
 	! [ -d "$_PATH_LOG" ] && mkdir -p "$_PATH_LOG"
 
-	f_info="$_PATH_LOG/${_SCRIPTNAME}.info"
-	f_err="$_PATH_LOG/${_SCRIPTNAME}.err"
-	f_debug="$_PATH_LOG/${_SCRIPTNAME}.debug"
+	_SF_INF="$_PATH_LOG/${_SCRIPTNAME}.info"
+	_SF_ERR="$_PATH_LOG/${_SCRIPTNAME}.err"
+	_SF_BUG="$_PATH_LOG/${_SCRIPTNAME}.debug"
 
 	opt=${1:-$S_TRACE}
 	opt=${opt:-$S_TRACEOPT}
 
 	case "$opt" in
-		#				stderror																	sdtout							info									debug
-		#				2																				1									4										6
-		quiet)		exec 2> >(tee -a "$f_err" "$f_info")							1>&								4>>"$f_info"					6>/dev/null;;
-		info)			exec 2> >(tee -a "$f_err" "$f_info")							1> >(tee -a "$f_info")	4> >(tee -a "$f_info")		6>/dev/null;;
-		verbose)	exec 2> >(tee -a "$f_err" "$f_info" "$f_debug")		1> >(tee -a "$f_info")	4> >(tee -a "$f_info")		6>>"$f_debug";;
-		debug)	exec 2> >(tee -a "$f_err" "$f_info" "$f_debug")		1> >(tee -a "$f_info")	4> >(tee -a "$f_info")		6> >(tee -a "$f_debug");;
+		#				stderror														sdtout													info														debug
+		#				2																	1															4															6
+		quiet)		exec 2> >(tee -a "$_SF_ERR")						1>>"$_SF_INF"									4>>"$_SF_INF"									6>/dev/null;;
+		info)			exec 2> >(tee -a "$_SF_ERR" "$_SF_INF" )	1> >(tee -a "$_SF_INF")						4>&1													6>/dev/null;;
+		debug)	exec 2> >(tee -a "$_SF_ERR" "$_SF_BUG")	1> >(tee -a "$_SF_INF" "$_SF_BUG")	4> >(tee -a "$_SF_INF" "$_SF_BUG")	6>>"$_SF_BUG";;
+		full)			exec 2> >(tee -a "$_SF_ERR" "$_SF_BUG")	1> >(tee -a "$_SF_INF" "$_SF_BUG")	4> >(tee -a "$_SF_INF" "$_SF_BUG")	6> >(tee -a "$_SF_BUG");;
 	esac
 }
 
 ################################  MAIN
+
+# singleton
+S_INC_FUNCTIONS="true"
 
 # colors
 white='\e[0;0m'; red='\e[0;31m'; green='\e[0;32m'; blue='\e[0;34m'; magenta='\e[0;35m'; yellow='\e[0;33m'
diff --git a/lxcx b/lxcx
--- a/lxcx
+++ b/lxcx
@@ -1,14 +1,18 @@
 #!/bin/bash
 #
-# Provides:             lxcx
-# Short-Description:    functions over lxc to manipulate containers
-# Description:          functions over lxc to manipulate containers
+# Provides:						lxcx
+# Short-Description:		functions over lxc to manipulate containers
+# Description:					functions over lxc to manipulate containers
 
 ################################ GLOBAL FUNCTIONS
-S_TRACE=verbose
+S_TRACE=debug
 
-! [[ "$S_GLOBAL_FUNCTIONS" && -f $S_GLOBAL_FUNCTIONS ]] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
-. $S_GLOBAL_FUNCTIONS
+if [ -z $S_INC_FUNCTIONS ]; then
+	S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
+	! [ -f "$S_GLOBAL_FUNCTIONS" ] && echo -e "error - Unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1
+	. "$S_GLOBAL_FUNCTIONS"
+	. "$S_PATH_SCRIPT/inc-lxc"
+fi
 
 ################################  VARIABLES
 
@@ -16,37 +20,22 @@ usage="lxcx : manage containers
 the container name can be one or few name (separate with space)
 and a special name 'all' to select all containers
 
-Options:
-	-a,--all             select all containers for action
-	-r, --regexp     the selection for container name is made with regexp.
-	                       BE CAREFUL: limit the begin & the end of regexp
-	-f, --force         force certain actions (delete, stop, restart, publish...)
-	-h, --help        show usage of functions
-	-q, --quiet       don't show any infomations except interaction informations
-	-d, --debug     output in screen & in file debug informations
+Global usage:    lxcx <args> [action] [containers]
+	start			<ct name>
+	stop			<ct name>
+	restart		<ct name>
+	delete		<ct name>	if option '--force' is given, running container are also deleted
 
-Global usage:    lxcx <options> [action] [containers]
-	start   <ct name>
-	stop    <ct name>
-		if option '--force' is given, stopped container are running
-	restart <ct name>
-		if option '--force' is given, stopped container are running
-	delete	<ct name>
-		if option '--force' is given, running container are also deleted
+args:
+	-r, --regexp <regexp>    the selection for container name is made with regexp.
+							BE CAREFUL: limit the begin & the end of regexp
+	-a,--all				select all containers for action
+	-f, --force         	force certain actions (delete, stop, restart, publish...)
 
-Init usage:    lxcx init <options> [image] [containers]
-		Initialize a container from an image for a name
-
-	copy <source name> <ip id> <destination name>
-		Initialize a container with his name, IP id from image
-		if name, ip id & image don't pass to function, it will asking
-
-	publish	<ct name>
-		Create an image from container, if image already exists, add '_Ymd' to name
-		if option '--force' is given, running container are stopped before
-		if option '--delete' is given, existing image will be replaced
+	-h, --help			show usage of functions
+	-q, --quiet		don't show any infomations except interaction informations
+	-d, --debug		output in screen & in file debug informations
 "
-
 
 ################################  FUNCTION
 
@@ -58,39 +47,39 @@ __select() {
 	_echoD "${FUNCNAME}() \$2=$2"
 
 	# all
-	if [ "${LXCX_ALL}" = "all" ]; then
-		cts_tmp="$2"
+	if [ "${ALL}" = "all" ]; then
+		cts="$2"
 	else
 		# named containers
 		cts_tmp="$1"
-		_echoD "${FUNCNAME}() named cts_tmp=${cts_tmp}"
+		#_echoD "${FUNCNAME}() named cts_tmp=${cts_tmp}"
 		# regexped containers
-		for regexp in $LXCX_REGEXP; do
+		for regexp in $REGEXP; do
 			cts_tmp="${cts_tmp} $(lxc list --format=json ${regexp} | jq -r '.[].name' |xargs)"
 		done
-		_echoD "${FUNCNAME}() all cts_tmp=${cts_tmp}"
+		#_echoD "${FUNCNAME}() all cts_tmp=${cts_tmp}"
 		cts_tmp=`echo ${cts_tmp} | tr " " "\n" | sort -u | xargs`
+		# filters containers
 		for ct in $cts_tmp; do
 			[[ " $2 " = *" $ct "* ]] && cts="${cts} ${ct}"
 		done
-		_echoD "${FUNCNAME}() unique cts=${cts}"
-		echo "$cts"
 	fi
+	_echoD "${FUNCNAME}() unique cts=${cts}"
+	echo "$cts"
 }
 
 __start() {
 	local cmd cts cts_selected
 	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() LXCX_ALL=$LXCX_ALL LXCX_FORCE=$LXCX_FORCE LXCX_REGEXP=$LXCX_REGEXP"
+	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
-	cts_selected="$(lxc list --format=json | jq -r '.[] | select(.status == "Stopped").name' |xargs)"
+	cts_selected=`__lxc_list_stopped`
 	cts=`__select "$*" "$cts_selected"`
 	_echoD "${FUNCNAME}() cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc start ${cts}"
 		_echoD "${FUNCNAME}() cmd=${cmd}"
-		exit
 		$cmd
 	fi
 }
@@ -98,16 +87,15 @@ __start() {
 __stop() {
 	local cmd cts cts_selected
 	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() LXCX_ALL=$LXCX_ALL LXCX_FORCE=$LXCX_FORCE LXCX_REGEXP=$LXCX_REGEXP"
+	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
-	cts_selected="$(lxc list --format=json | jq -r '.[] | select(.status == "Running").name' |xargs)"
+	cts_selected=`__lxc_list_running`
 	cts=`__select "$*" "$cts_selected"`
 	_echoD "${FUNCNAME}() cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc stop ${cts}"
 		_echoD "${FUNCNAME}() cmd=${cmd}"
-		exit
 		$cmd
 	fi
 }
@@ -115,16 +103,15 @@ __stop() {
 __restart() {
 	local cmd cts cts_selected
 	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() LXCX_ALL=$LXCX_ALL LXCX_FORCE=$LXCX_FORCE LXCX_REGEXP=$LXCX_REGEXP"
+	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
-	cts_selected="$(lxc list --format=json | jq -r '.[] | select(.status == "Running").name' |xargs)"
+	cts_selected=`__lxc_list_running`
 	cts=`__select "$*" "$cts_selected"`
 	_echoD "${FUNCNAME}() cts=${cts}"
 
 	if [ "${cts}" ];then
 		cmd="lxc restart ${cts}"
 		_echoD "${FUNCNAME}() cmd=${cmd}"
-		exit
 		$cmd
 	fi
 }
@@ -132,49 +119,48 @@ __restart() {
 __delete() {
 	local cmd cts cts_selected
 	_echoD "${FUNCNAME}() \$@=$@"
-	_echoD "${FUNCNAME}() LXCX_ALL=$LXCX_ALL LXCX_FORCE=$LXCX_FORCE LXCX_REGEXP=$LXCX_REGEXP"
+	_echoD "${FUNCNAME}() ALL=$ALL FORCE=$FORCE REGEXP=$REGEXP"
 
-	if [ "${LXCX_FORCE}" ]; then
-		cts_selected="$(lxc list --format=json | jq -r '.[].name' |xargs)"
+	if [ "${FORCE}" ]; then
+		cts_selected=`__lxc_list_existing`
 	else
-		cts_selected="$(lxc list --format=json | jq -r '.[] | select(.status == "Stopped").name' |xargs)"
+		cts_selected=`__lxc_list_stopped`
 	fi
 	cts=`__select "$*" "$cts_selected"`
 	_echoD "${FUNCNAME}() cts=${cts}"
 
 	if [ "${cts}" ];then
-		cmd="lxc delete ${LXCX_FORCE:+--$LXCX_FORCE} ${cts}"
+		cmd="lxc delete ${FORCE:+--$FORCE} ${cts}"
 		_echoD "${FUNCNAME}() cmd=${cmd}"
-		exit
 		$cmd
 	fi
 }
 
 __main() {
+	_echod "$0 ${FUNCNAME}()"
+	local opts_given opts_short opts_long opts action
+	local  ALL FORCE REGEXP
 
-	cmd_opts=
-	ddate=`date +%s`
 	opts_given="$@"
 	opts_short="afr:hdq"
 	opts_long="all,force,regexp:,help,quiet,debug"
-	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@" 2>/tmp/${0##*/}-${ddate}) || _exite "$(</tmp/${0##*/}-${ddate})'"
+	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@")
 	eval set -- "${opts}"
 
-	_echoD "opts_given=$opts_given opts=$opts"
+	_echoD "${FUNCNAME}() opts_given=$opts_given opts=$opts"
 
 	while [ "$1" != "--" ]
 	do
 		case "$1" in
 			-a|--all)
-				LXCX_ALL="all"
+				ALL="all"
 				;;
 			-f|--force)
-				force=force
-				LXCX_FORCE="force"
+				FORCE="force"
 				;;
 			-r|--regexp)
 				shift
-				LXCX_REGEXP="${LXCX_REGEXP} $1"
+				REGEXP="${REGEXP} $1"
 				;;
 			--help)
 				echo "$usage"
@@ -195,10 +181,11 @@ __main() {
 
 	action="$1"
 	shift
-	_echoD "${FUNCNAME}() LXCX_ALL='$LXCX_ALL' LXCX_FORCE='$LXCX_FORCE' LXCX_REGEXP='$LXCX_REGEXP' "
-	_echoD "${FUNCNAME}() action='$action' cmd_opts='$cmd_opts'"
+	_echoD "${FUNCNAME}() ALL='$ALL' FORCE='$FORCE' REGEXP='$REGEXP' "
+	_echoD "${FUNCNAME}() action='$action'"
 
-	if [[ " delete init publish restart start stop " = *" $action "* ]]; then
+	[ -z "$action" ] && _exite "You have to give an action to execute"
+	if [[ " start stop restart delete " = *" $action "* ]]; then
 		# call action with arguments
 		__$action "$@"
 	else
@@ -207,10 +194,6 @@ __main() {
 }
 
 ################################  MAIN
-
-LXCX_REGEXP=
-LXCX_FORCE=
-LXCX_ALL=
 
 __main "$@"
 
