add apostrophes to variables

diff --git a/lxcx b/lxcx
--- a/lxcx
+++ b/lxcx
@@ -9,7 +9,7 @@
 
 S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}"
 ! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1
-! . "$S_PATH_SCRIPT/inc-lxc.sh" && echo -e "[error] - Unable to source file '$S_PATH_SCRIPT/inc-lxc.sh' from '${BASH_SOURCE[0]}'" && exit 1
+! . "${S_PATH_SCRIPT}/inc-lxc.sh" && echo -e "[error] - Unable to source file '${S_PATH_SCRIPT}/inc-lxc.sh' from '${BASH_SOURCE[0]}'" && exit 1
 
 ########################  VARIABLES
 
@@ -193,7 +193,7 @@ __opts() {
 
 __main()
 {	_echod "======================================================"
-	_echod "$(ps -o args= $PPID)"
+	_echod "$(ps -o args= ${PPID})"
 	local ACTION= ALL= FORCE= RUNNING= STOPPED= CTS=
 	local ACTIONS="delete list publish purge restart start stop"
 	local CTS_RUNNING=`lxc list -f csv -c n status=Running`
